backend:
  name: github
  repo: cwacht/m3-playbook-prototype
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  use_graphql: true

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Phases
    name: phases
    folder: _pages/m3
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'm3'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: SubPhases
    name: subPhases
    folder: _pages/m3/subPhase
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'm3-activities'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Data
    name: data
    folder: _data/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Code", name: "body", widget: "code"}
