backend:
  name: github
  repo: cwacht/m3-playbook-prototype
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  use_graphql: true

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Phases
    name: phases
    folder: _pages/m3/phase
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: "select", options: ["m3"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name of Phase", name: "phaseName", widget: "string"}
      - {label: "Objective", name: "objective", widget: "text"}
      - label: "Downloads"
        name: "downloads"
        widget: "object"
        summary: '{{fields.image}}'
        fields:
          - {label: "Playbook Link", name: "playbook", widget: "string"}
          - {label: "Guidance Link", name: "guidance", widget: "string"}
          - {label: "Tollgate Link", name: "tollgate", widget: "string"}
      - label: "Subphases"
        name: "subphases"
        widget: "list"
        summary: '{{fields.name}}'
        minimize_collapsed: true
        fields:
          - label: "Subphase"
            name: "subphase"
            widget: "relation"
            collection: "subphases"
            search_fields: ["name"]
            display_fields: ["name"]
            value_field: "name"
      - label: "Documentation"
        name: "documentation"
        widget: "list"
        summary: '{{fields.name}}'
        minimize_collapsed: true
        fields:
          - {label: Name, name: name, widget: string}
          - {label: URL, name: url, widget: string, required: false}
      - label: "Tollgate Info"
        name: "tollageInfo"
        widget: "list"
        summary: '{{fields.name}}'
        minimize_collapsed: true
        fields:
          - {label: Name, name: name, widget: string}
          - {label: URL, name: url, widget: string, required: false}
      - label: "Exit Criteria"
        name: "exitCriteria"
        widget: "list"
        summary: '{{fields.name}}'
        minimize_collapsed: true
        fields:
          - {label: Name, name: name, widget: string}
          - {label: URL, name: url, widget: string, required: false}
  - label: Subphases
    name: subphases
    folder: _pages/m3/subphase
    create: true
    slug: "{{name}}" #"{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'm3-activities'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Data
    name: data
    folder: _data/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Code", name: "body", widget: "code"}
