backend:
  name: github
  repo: cwacht/m3-playbook-prototype
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  use_graphql: true

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Phases
    name: phases
    folder: _pages/m3/phase
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'm3'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name of Phase", name: "phaseName", widget: "string"}
      - {label: "Objective", name: "objective", widget: "text"}
      - label: "Downloads"
        name: "downloads"
        widget: "object"
        summary: '{{fields.image}}'
        fields:
          - {label: "Playbook Link", name: "playbook", widget: "string"}
          - {label: "Guidance Link", name: "guidance", widget: "string"}
          - {label: "Tollgate Link", name: "tollgate", widget: "string"}
      - label: "Documentation"
        name: "documentation"
        widget: "list"
        summary: '{{fields.name}}'
        fields:
          - {label: Name, name: name, widget: string}
          - {label: URL, name: url, widget: string, required: false}
  - label: SubPhases
    name: subPhases
    folder: _pages/m3/subPhase
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'm3-activities'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Data
    name: data
    folder: _data/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Code", name: "body", widget: "code"}
